# Generated by Django 4.2.5 on 2023-10-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='portrait',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='portrait',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
