# Generated by Django 4.2.5 on 2023-10-01 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'clinic_human',
            },
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vet_clinic.human')),
            ],
            options={
                'db_table': 'clinic_pet_owner',
            },
            bases=('vet_clinic.human',),
        ),
        migrations.CreateModel(
            name='VetDoctor',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vet_clinic.human')),
                ('speciality', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'clinic_doctor',
            },
            bases=('vet_clinic.human',),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('animal_type', models.CharField(blank=True, max_length=30, null=True)),
                ('treatment', models.TextField(blank=True, max_length=1000, null=True)),
                ('menace', models.BooleanField(default=True)),
                ('pet_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet_clinic.petowner')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vet_clinic.vetdoctor')),
            ],
            options={
                'db_table': 'clinic_pet',
            },
        ),
    ]
